vim.g.mapleader = " "
vim.keymap.set("n", "<C-s>", vim.cmd.wa)
vim.keymap.set("n", "<leader>e", vim.cmd.Ex)
vim.keymap.set("n", "<leader>h", vim.cmd.split)
vim.keymap.set("n", "<leader><leader>", vim.cmd.so)
vim.keymap.set("n", "<CR>", vim.cmd.noh, { silent = true })
vim.keymap.set("n", "<leader>gs", vim.cmd.Git);
vim.keymap.set("n", "<leader>q", function() vim.cmd("q!") end)
vim.keymap.set("n", "?", function() vim.diagnostic.open_float() end)
vim.keymap.set("n", "<leader>n", function() vim.lsp.buf.format() end)
vim.keymap.set("n", "<leader>s", ":Vexplore!<CR>", { silent = true })
vim.keymap.set("n", "<C-Left>", ":vertical resize +25<CR>", { silent = true })
vim.keymap.set("n", "<C-Right>", ":vertical resize -25<CR>", { silent = true })
vim.keymap.set("n", "<C-Up>", ":horizontal resize -5<CR>", { silent = true })
vim.keymap.set("n", "<C-Down>", ":horizontal resize +5<CR>", { silent = true })
vim.keymap.set("n", "n", "nzzzv", { noremap = true })
vim.keymap.set("n", "N", "Nzzzv", { noremap = true })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { noremap = true })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { noremap = true })
vim.keymap.set("n", "<A-j>", ":m .+1<CR>==", { noremap = true, silent = true })
vim.keymap.set("n", "<A-k>", ":m .-2<CR>==", { noremap = true, silent = true })
vim.keymap.set("i", "<A-k>", "<Esc>:m .-2<CR>==gi", { noremap = true, silent = true })
vim.keymap.set("i", "<A-j>", "<Esc>:m .+1<CR>==gi", { noremap = true, silent = true })
